### ISSUE TITLE
[semantic-release][semantic/github]

### ISSUE THREAD

**Issue by s-ong-c** [s-ong-c/tip#27]
### github

- [https://github.com/semantic-release/semantic-release](https://github.com/semantic-release/semantic-release)

- @semantic-release/npm
- @semantic-release/release-notes-generator
- @semantic-release/commit-analyzer
- @semantic-release/git
- @semantic-release/github
```js
{
  "branches": [
    {"name": "main"},
    {"name": "alpha", "prerelease": true},
    {"name": "beta", "prerelease": true}
  ],
  "repositoryUrl": "https://github.com/FFM-TEAM/design-system",
  "debug": "true",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    [
      "@semantic-release/github", {
        "assets": ["dist/**", "esm/**", "package.json"],
        "successComment": "🎉 This PR is included in version ${nextRelease.version} 🎉 "
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": ["package.json", "yarn.lock"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
}
```

[CI CD]

```yml
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.0'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check Lint
        run: yarn lint
      - name: Run Test
        run: yarn test
      - name: Build Package
        run: yarn build
      - name: Release to npm registry
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release

```

### Gitlab

- @semantic-release/npm
- @semantic-release/release-notes-generator
- @semantic-release/commit-analyzer
- @semantic-release/git
- @semantic-release/gitlab

[CI CD]
```
{
  "branches": [
    {"name": "master"},
    {"name": "alpha", "prerelease": true},
    {"name": "beta", "prerelease": true}
  ],
  "repositoryUrl": "",
  "debug": "true",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/gitlab", {
        "assets": ["dist/**", "esm/**", "package.json"],
        "successComment": "🎉 This PR is included in version ${nextRelease.version} 🎉 "
      }
    ],
    "@semantic-release/npm",
    [
      "@semantic-release/git",
      {
        "assets": ["package.json", "yarn.lock"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
}

```
[gitlab-ci.yml]

```
release:
  image: node:13
  stage: release
  script:
    - yarn build
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - yarn semantic-release
    - |
      {
        npm publish &&
        echo "Successfully published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} to GitLab's NPM registry: ${CI_PROJECT_URL}/-/packages"
      } || {
        echo "No new version of ${NPM_PACKAGE_NAME} published. This is most likely because version ${NPM_PACKAGE_VERSION} already exists in GitLab's NPM registry."
      }

```
